version: '3.7'

services:
    postgres:
        image: postgres:9.6
        container_name: postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./database/:/var/lib/postgresql/data/
        ports:
            - ${POSTGRES_PORT}:5432
        networks:
            - mlremote

    airflow:
        build: ./airflow/
        container_name: airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
        volumes:
            - ./airflow/:/root/airflow/
        ports:
            - ${AIRFLOW_PORT}:8080
        networks:
            - mlremote
 
    jupyterlab:
        build: ./jupyterlab/ 
        container_name: jupyterlab
        restart: always
        volumes:
            - ./jupyterlab/scripts/:/jupyterlab/ 
            - ./airflow/dags/:/jupyterlab/dags
        ports:
            - ${JUPYTER_PORT}:6060
        networks:
            - mlremote
 

networks:
    mlremote:
        driver: bridge
