version: '3.7'

services:
    postgres:
        image: postgres:9.6
        container_name: postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./database/:/var/lib/postgresql/data/

    airflow:
        build: ./airflow/
        container_name: airflow
        restart: always
        depends_on:
            - postgres
        volumes:
            - ./airflow/dags/:/usr/local/airflow/dags/
        ports:
            - "8080:8080"
        healthcheck:
            test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
            interval: 30s
            timeout: 30s
            retries: 5

    jupyterlab:
        build: ./jupyterlab/ 
        container_name: jupyterlab
        restart: always
        volumes:
            - ./jupyterlab/scripts/:/jupyterlab/ 
        ports:
            - "6060:6060"

